apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: samsar
type: Opaque
stringData:
  SECRET_KEY: myScretLKeY

  MONGODB_CONNECTION_STRING: mongodb+srv://boussabatmarwen9:frEA42FLaLk0jlvC@cluster0.9k8pdvg.mongodb.net/WEB_PROJECT?retryWrites=true&w=majority&appName=Cluster0
  MONGODB_PASSWORD: frEA42FLaLk0jlvC

  MAILJET_API_KEY: b01988a9b94980291b6688417dd2b1b7
  MAILJET_SECRET_KEY: 6fbe227481962e63c73c613683d5d49f

  CLOUDINARY_CLOUD_NAME: dgmaxi7wu
  CLOUDINARY_API_KEY: "556597567483439"
  CLOUDINARY_API_SECRET: 6USeXasJKedtJssQUesTWjveEOg 