apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: samsar-backend
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - samsar

  selector:
    matchLabels:
      app: backend-service-url

  endpoints:
    - port: http
      path: /metrics
      interval: 15s