apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: rabbitmq
  namespace: monitoring
  labels:
    release: kube-prometheus-stack

spec:
  namespaceSelector:
    matchNames:
      - samsar

  selector:
    matchLabels:
      app: rabbitmq-service-url

  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s